/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and version, no authentication required */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP/HTTP protobuf trace ingest
         * @description The canonical OTLP endpoint. Point any OpenTelemetry SDK at it with `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and an authorization header. A 200 means the spans are committed and fsynced.
         */
        post: operations["ingestTraces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/otel/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP ingest under the Langfuse SDK's path
         * @description The same endpoint as `/v1/traces`, at the path a Langfuse SDK sends to. Setting `LANGFUSE_HOST` to a tracepad is the whole migration.
         */
        post: operations["ingestTracesLangfuse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This endpoint map
         * @description Where an agent that has never seen this API starts: every endpoint with a one-line description, plus the link to this document. Needs no key: it says what the API is, never what is in it.
         */
        get: operations["apiIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The OpenAPI 3.1 document for this API */
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version, uptime, database size and ingest counters since start
         * @description Self-diagnosis without a metrics stack. The counters are in-memory and cover this process only, which is what `counters.since` says. Row counts and counters are the asking project's own — `payloads` is absent because it cannot be attributed to one, `projects` is how many tenants share this process (naming none of them), and `size_bytes` is the whole deployment's file on disk.
         */
        get: operations["system"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces newest first, filtered and cursor-paginated
         * @description Rows carry the aggregate columns and never a payload — a listing is for choosing what to fetch. To read one trace whole, follow with `GET /api/v1/traces/{id}`; to go straight to the newest match, use `GET /api/v1/traces/last`.
         */
        get: operations["listTraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The newest trace matching the filters, whole
         * @description The task shortcut: `?status=error&expand=io` answers "why did the last run fail" in one round trip instead of list, filter, get, and one get per observation. Takes every filter of the listing and returns exactly what `GET /api/v1/traces/{id}` returns.
         */
        get: operations["lastTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One trace with its observations as a nested tree
         * @description Children are nested inside their parents, siblings ordered by start time. An observation whose parent has not arrived yet renders at the root with its `parent_observation_id` intact. Payloads ride only with `?expand=io`.
         */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observations/{id}/io": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The whole input, output and metadata of one observation
         * @description The one endpoint no byte budget applies to: it exists to be the `full` target of every truncation marker, and a budget here would recurse. A span id is unique only inside its trace, so pass `?trace_id=` when the same id appears in more than one — every truncation marker already carries the pair.
         */
        get: operations["observationIO"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One session: its totals and its traces
         * @description A session is not a stored entity but the set of traces that named it. Every aggregate counts traces: `error_count` is how many of the session's traces failed, not how many spans did.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts, errors, cost and latency percentiles per bucket
         * @description Computed on the fly, with exact percentiles. `unit` says what a bucket counts: grouping by hour, day or environment counts traces, and grouping by model counts observations, because a trace has no model. An empty range answers with no buckets rather than with fabricated zero rows.
         */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scores, filtered and cursor-paginated */
        get: operations["listScores"];
        put?: never;
        /**
         * Write one score or an array of them
         * @description An array is all-or-nothing: one transaction, and one 400 naming the first invalid item. A 201 means the rows are on disk. No Content-Type is required.
         */
        post: operations["createScores"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one score */
        get: operations["getScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List prompt names with where their labels point */
        get: operations["listPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one prompt by version, by label, or the latest
         * @description With neither `version` nor `label`, the highest version. `latest` is a virtual label meaning the same thing; there is no implicit `production`.
         */
        get: operations["getPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a prompt's versions, newest first
         * @description Without the bodies: a version list is for picking and diffing.
         */
        get: operations["listPromptVersions"];
        put?: never;
        /**
         * Append a version to a prompt
         * @description Versions are append-only and numbered inside the write transaction, so parallel creates produce 1..N with no gaps. A name's type is fixed by its first version.
         */
        post: operations["createPromptVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{name}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unified diff between two versions of a prompt
         * @description A unified text patch over the pretty-printed `prompt` and `config` of the two versions — the format every consumer already reads. Empty when the two versions are identical.
         */
        get: operations["promptDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{name}/labels/{label}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Point a label at a version
         * @description The deploy path: promote by moving `production` forward, roll back by moving it back. One row, no new version.
         */
        put: operations["putPromptLabel"];
        post?: never;
        /** Remove a label */
        delete: operations["deletePromptLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description The admin token sees every project; a project key sees its own and nothing else.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project and its first key pair
         * @description The secret key is in this response and in no other: only its hash is stored. A name inside another project's grace window is a 409 naming the restorable one.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One project with its retention windows
         * @description A soft-deleted project's own key still reaches this one, so that a caller about to restore can see what it is restoring and until when.
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a project, restorable for seven days
         * @description The keys stop authenticating immediately and the project vanishes from listings; the data is destroyed by the sweeper after a fixed seven-day grace. Admin token only, even for one's own project. Without `confirm` it answers with the preview.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /**
         * Rename a project or move its retention windows
         * @description Renaming needs the admin token; the windows are the project's own business. `null` means keep forever. A window that shrinks is destructive: without `confirm` it answers with the preview, and it applies only when `confirm` echoes the project's name.
         */
        patch: operations["patchProject"];
        trace?: never;
    };
    "/api/v1/projects/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo a soft delete inside its grace window
         * @description No confirmation: it destroys nothing. Reachable with the project's own key even while deleted, so that a deployment without an admin token can still undo one.
         */
        post: operations["restoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a project's public keys
         * @description The secrets are not here because they are not anywhere: only their hashes are stored.
         */
        get: operations["listKeys"];
        put?: never;
        /**
         * Mint a key pair; the secret is shown once
         * @description Several active pairs are what makes rotation zero-downtime: create the new one, move the SDKs, revoke the old.
         */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/keys/{public_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one key pair
         * @description Revoking a project's last key stops its ingest, so that one is a dry run until `confirm` echoes the project's name.
         */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/users/{user_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase everything stored about one user
         * @description Erases the queryable stores synchronously: the traces filed under the user id, their observations, payloads and scores. Raw OTLP bodies are not touched — they are an archive expiring on the raw retention window, which docs/retention.md documents together with what that means for an erasure request. Without `confirm` it answers with the preview; the echo here is the user id.
         */
        delete: operations["eraseUserData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The one error shape the whole surface uses */
        Error: {
            error: string;
        };
        /** @description A trace as it appears in a listing: aggregates only, never a payload. A field the trace never carried is absent rather than empty. */
        TraceRow: {
            id: string;
            name?: string;
            user_id?: string;
            session_id?: string;
            environment: string;
            tags?: string[];
            /**
             * Format: date-time
             * @description When the earliest observation of the trace started
             */
            timestamp?: string;
            /** @description Summed over the observations whose client provided cost; absent when none did */
            total_cost?: number;
            latency_ms?: number;
            error_count: number;
            observation_count: number;
        };
        Trace: components["schemas"]["TraceRow"] & {
            metadata?: Record<string, never>;
            observations: components["schemas"]["Observation"][];
            expansion?: components["schemas"]["Expansion"];
        };
        /** @description One span. `children` holds the spans that named it as their parent and is absent for a leaf. */
        Observation: {
            id: string;
            /** @description The observation this one ran under, whenever it named one. Nested children carry it too; an observation whose parent is not in this trace renders at the root and still carries it. */
            parent_observation_id?: string;
            /** @enum {string} */
            type: "span" | "generation" | "event";
            name?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            model?: string;
            model_parameters?: Record<string, never>;
            /** @enum {string} */
            level: "DEBUG" | "DEFAULT" | "WARNING" | "ERROR";
            status_message?: string;
            usage?: Record<string, never>;
            cost_details?: Record<string, never>;
            input?: components["schemas"]["Truncation"] | unknown;
            output?: components["schemas"]["Truncation"] | unknown;
            metadata?: components["schemas"]["Truncation"] | Record<string, never>;
            children?: components["schemas"]["Observation"][];
        };
        /** @description Present only when `?expand=io` was refused: a trace with more payloads than the budget can carry markers for gets none of them and this instead. Nothing is unreachable — the tree lists every observation id — and `budget_needed` is what to retry `?budget=` with. */
        Expansion: {
            /** @constant */
            expanded: false;
            /** @description How many payloads the trace holds. */
            payloads: number;
            /** @description The budget that would carry a marker for each of them. Never clamped to the maximum, so it may exceed what `?budget=` accepts. */
            budget_needed: number;
            /** @description Whether `budget_needed` is a budget this server would accept. False means no budget can carry this many markers — read the payloads one at a time instead. */
            retryable: boolean;
            reason: string;
        };
        /** @description A payload too large for this response's budget. `full` is the URL that returns it whole; `trace_id` and `observation_id` are the same target for a consumer that speaks tools rather than URLs. */
        Truncation: {
            /** @constant */
            truncated: true;
            /** @description The payload's full size in bytes */
            size?: number;
            /** @description A prefix of the payload, cut on a UTF-8 boundary */
            preview?: string;
            trace_id: string;
            observation_id: string;
            full: string;
        };
        /** @description One judgement. A score needs a trace or a session, and either a `value` or a `string_value`. */
        ScoreInput: {
            /** @description Generated when absent; writing the same id again replaces the score */
            id?: string;
            trace_id?: string;
            observation_id?: string;
            session_id?: string;
            name: string;
            /**
             * @description Inferred when absent: a `value` makes it numeric, a `string_value` makes it text
             * @enum {string}
             */
            data_type?: "numeric" | "boolean" | "categorical" | "text";
            value?: number;
            string_value?: string;
            comment?: string;
            metadata?: unknown;
            /**
             * Format: date-time
             * @description Event time; defaults to receive time
             */
            timestamp?: string;
        };
        Score: {
            id: string;
            trace_id?: string;
            observation_id?: string;
            session_id?: string;
            name: string;
            /** @enum {string} */
            data_type: "numeric" | "boolean" | "categorical" | "text";
            value?: number;
            string_value?: string;
            comment?: string;
            metadata?: unknown;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            created_at: string;
        };
        Prompt: {
            name: string;
            version: number;
            /** @enum {string} */
            type: "text" | "chat";
            /** @description Stored and returned verbatim; interpolation is the client's job */
            prompt: unknown;
            config?: Record<string, never>;
            commit_message?: string;
            labels: string[];
            /** Format: date-time */
            created_at: string;
        };
        Label: {
            label: string;
            version: number;
        };
        /** @description A project with its retention windows. `deleted_at` and `purge_at` are present only while a soft delete is inside its grace window. */
        Project: {
            id: string;
            name: string;
            /** @description null means the data is kept forever, which is the default */
            retention_days: number | null;
            /** @description null means raw follows retention_days */
            raw_retention_days: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            deleted_at?: string;
            /**
             * Format: date-time
             * @description When the sweeper destroys the data; seven days after the delete, and not configurable
             */
            purge_at?: string;
        };
        /** @description A freshly minted key pair. The secret appears here and nowhere else, ever. */
        NewKey: {
            public_key: string;
            secret_key: string;
            /** Format: date-time */
            created_at?: string;
            note?: string;
        };
        /** @description What a destructive request would do, which is what it does until it is confirmed */
        DryRun: {
            /** @constant */
            dry_run: true;
            would_delete: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description Arrival of the oldest affected row; absent when nothing is affected
             */
            oldest?: string;
            /** @description Send this back as `?confirm=` to make it happen */
            confirm: string;
            note?: string;
        };
        /** @description What a confirmed destructive request actually removed */
        Deletion: {
            /** @constant */
            dry_run: false;
            deleted: {
                [key: string]: number;
            };
        };
    };
    responses: {
        /** @description The request cannot mean what it says: an unknown query parameter, a malformed value, a limit out of range */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credentials do not resolve to a project */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such thing in this project */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credentials are good but do not reach this far: cross-project administration needs the admin token */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The stored state already answers differently: a name that is taken, a project that is already deleted */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description RFC 3339, inclusive. The range is half-open, so walking a timeline never reports a row twice. */
        From: string;
        /** @description RFC 3339, exclusive */
        To: string;
        /** @description Exact match on the environment a trace ran in */
        Environment: string;
        /** @description Out of range is a 400, not a silent clamp */
        Limit: number;
        /** @description The opaque `next_cursor` of the previous page */
        Cursor: string;
        /** @description `io` inlines each observation's input, output and metadata, each cut to an equal share of the remaining budget with a truncation marker naming the rest */
        Expand: "io";
        /** @description Byte budget for the payloads of this response; the structure is never truncated */
        Budget: number;
        PromptName: string;
        PromptLabel: string;
        ProjectID: string;
        /** @description The name of the project — or the id of the user — being destroyed. Without it the endpoint changes nothing and answers with a preview; a value that does not match is a 400 that also changes nothing. */
        Confirm: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        version: string;
                    };
                };
            };
        };
    };
    ingestTraces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
            };
        };
        responses: {
            /** @description Accepted; the body is an ExportTraceServiceResponse carrying partial_success when spans were skipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-protobuf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The body exceeded TRACEPAD_MAX_BODY_BYTES */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Content-Type is not application/x-protobuf */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The write queue is full; retry after the Retry-After delay */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ingestTracesLangfuse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-protobuf": string;
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-protobuf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    apiIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The endpoint map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        openapi: string;
                        endpoints: {
                            method: string;
                            path: string;
                            description: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    system: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What this process knows about itself */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                        go_version?: string;
                        /** Format: date-time */
                        started_at: string;
                        uptime_seconds: number;
                        database: {
                            /** @description The database file plus its write-ahead log, for the whole deployment */
                            size_bytes?: number;
                            /** @description Row counts within the asking project, plus `projects` as a bare tenant count */
                            rows?: {
                                [key: string]: number;
                            };
                        };
                        writer_queue?: {
                            waiting?: number;
                            capacity?: number;
                        };
                        response_budget_bytes?: number;
                        /** @description This project's ingest traffic since the process started */
                        counters: {
                            /** Format: date-time */
                            since?: string;
                            dialects?: {
                                [key: string]: {
                                    batches?: number;
                                    spans_stored?: number;
                                    spans_skipped?: number;
                                };
                            };
                            rejected_batches?: number;
                            unreadable_resource_spans?: number;
                            langfuse_ingestion_versions?: string[];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTraces: {
        parameters: {
            query?: {
                /** @description RFC 3339, inclusive. The range is half-open, so walking a timeline never reports a row twice. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339, exclusive */
                to?: components["parameters"]["To"];
                /** @description Exact match on the environment a trace ran in */
                environment?: components["parameters"]["Environment"];
                /** @description Exact match on the trace's user id */
                user_id?: string;
                /** @description Exact match on the trace's session id */
                session_id?: string;
                /** @description Exact match on the trace name */
                name?: string;
                /** @description Repeatable; a trace must carry every tag given */
                tag?: string[];
                /** @description `error` keeps traces with at least one failed observation, `ok` keeps the rest */
                status?: "error" | "ok";
                /** @description Keeps traces whose total cost is at least this much. A trace whose client provided no cost has none and never matches. */
                min_cost?: number;
                /** @description Comma-separated subset of the row fields. An unknown name is a 400. */
                fields?: string;
                /** @description Out of range is a 400, not a silent clamp */
                limit?: components["parameters"]["Limit"];
                /** @description The opaque `next_cursor` of the previous page */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of traces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        traces: components["schemas"]["TraceRow"][];
                        /** @description Pass back as `?cursor=` for the next page; null on the last one */
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    lastTrace: {
        parameters: {
            query?: {
                /** @description RFC 3339, inclusive. The range is half-open, so walking a timeline never reports a row twice. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339, exclusive */
                to?: components["parameters"]["To"];
                /** @description Exact match on the environment a trace ran in */
                environment?: components["parameters"]["Environment"];
                user_id?: string;
                session_id?: string;
                name?: string;
                tag?: string[];
                status?: "error" | "ok";
                min_cost?: number;
                /** @description `io` inlines each observation's input, output and metadata, each cut to an equal share of the remaining budget with a truncation marker naming the rest */
                expand?: components["parameters"]["Expand"];
                /** @description Byte budget for the payloads of this response; the structure is never truncated */
                budget?: components["parameters"]["Budget"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The newest matching trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Nothing matches; the message names the filters that found nothing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: {
                /** @description `io` inlines each observation's input, output and metadata, each cut to an equal share of the remaining budget with a truncation marker naming the rest */
                expand?: components["parameters"]["Expand"];
                /** @description Byte budget for the payloads of this response; the structure is never truncated */
                budget?: components["parameters"]["Budget"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The trace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    observationIO: {
        parameters: {
            query?: {
                /** @description Optional; required only when the span id is ambiguous within the project */
                trace_id?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payloads, whole */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        trace_id: string;
                        observation_id: string;
                        /** @description Whatever the client logged */
                        input?: unknown;
                        /** @description Whatever the client logged */
                        output?: unknown;
                        metadata?: Record<string, never>;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The span id appears in more than one trace; the message lists the candidates */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: {
                /** @description Out of range is a 400, not a silent clamp */
                limit?: components["parameters"]["Limit"];
                /** @description The opaque `next_cursor` of the previous page */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        trace_count: number;
                        /** @description Absent when no trace of the session carried a cost */
                        total_cost?: number;
                        error_count: number;
                        /** Format: date-time */
                        first_seen?: string;
                        /** Format: date-time */
                        last_seen?: string;
                        traces: components["schemas"]["TraceRow"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    stats: {
        parameters: {
            query?: {
                /** @description RFC 3339, inclusive. The range is half-open, so walking a timeline never reports a row twice. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339, exclusive */
                to?: components["parameters"]["To"];
                /** @description Exact match on the environment a trace ran in */
                environment?: components["parameters"]["Environment"];
                group_by?: "hour" | "day" | "model" | "environment";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        group_by: "hour" | "day" | "model" | "environment";
                        /** @enum {string} */
                        unit: "trace" | "observation";
                        buckets: {
                            key: string;
                            count: number;
                            error_count: number;
                            /** @description Absent when nothing in the bucket carried a cost */
                            total_cost?: number;
                            latency_ms: {
                                p50?: number | null;
                                p95?: number | null;
                            };
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listScores: {
        parameters: {
            query?: {
                trace_id?: string;
                observation_id?: string;
                session_id?: string;
                name?: string;
                data_type?: "numeric" | "boolean" | "categorical" | "text";
                /** @description RFC 3339, inclusive. The range is half-open, so walking a timeline never reports a row twice. */
                from?: components["parameters"]["From"];
                /** @description RFC 3339, exclusive */
                to?: components["parameters"]["To"];
                /** @description Out of range is a 400, not a silent clamp */
                limit?: components["parameters"]["Limit"];
                /** @description The opaque `next_cursor` of the previous page */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of scores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        scores: components["schemas"]["Score"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createScores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreInput"] | components["schemas"]["ScoreInput"][];
            };
        };
        responses: {
            /** @description Written */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The write queue is full; retry after the Retry-After delay */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Score"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPrompts: {
        parameters: {
            query?: {
                /** @description Out of range is a 400, not a silent clamp */
                limit?: components["parameters"]["Limit"];
                /** @description The opaque `next_cursor` of the previous page */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of prompt names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        prompts: {
                            name: string;
                            /** @enum {string} */
                            type: "text" | "chat";
                            latest_version: number;
                            labels: {
                                [key: string]: number;
                            };
                            /** Format: date-time */
                            updated_at: string;
                        }[];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPrompt: {
        parameters: {
            query?: {
                version?: number;
                label?: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prompt version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPromptVersions: {
        parameters: {
            query?: {
                /** @description Out of range is a 400, not a silent clamp */
                limit?: components["parameters"]["Limit"];
                /** @description The opaque `next_cursor` of the previous page */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        versions: {
                            version: number;
                            commit_message?: string;
                            labels: string[];
                            /** Format: date-time */
                            created_at: string;
                        }[];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createPromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Required on the first version of a name
                     * @enum {string}
                     */
                    type?: "text" | "chat";
                    /** @description A string for a text prompt, an array of {role, content} messages for a chat one */
                    prompt: unknown;
                    config?: Record<string, never>;
                    commit_message?: string;
                    labels?: string[];
                };
            };
        };
        responses: {
            /** @description The version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    promptDiff: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        from: number;
                        to: number;
                        diff: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putPromptLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
                label: components["parameters"]["PromptLabel"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: number;
                };
            };
        };
        responses: {
            /** @description Where the label points now */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePromptLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["PromptName"];
                label: components["parameters"]["PromptLabel"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version the label pointed at */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description `deleted` adds soft-deleted projects with their purge dates. Admin token only. */
                include?: "deleted";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The projects the caller may see */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: components["schemas"]["Project"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description The project and its one-time secret */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"] & components["schemas"]["NewKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: {
                /** @description The name of the project — or the id of the user — being destroyed. Without it the endpoint changes nothing and answers with a preview; a value that does not match is a 400 that also changes nothing. */
                confirm?: components["parameters"]["Confirm"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dry run: what deleting it would eventually destroy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRun"];
                };
            };
            /** @description Deleted, with the date the data is purged */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    patchProject: {
        parameters: {
            query?: {
                /** @description The name of the project — or the id of the user — being destroyed. Without it the endpoint changes nothing and answers with a preview; a value that does not match is a 400 that also changes nothing. */
                confirm?: components["parameters"]["Confirm"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Admin token only */
                    name?: string;
                    /** @description How long a trace is kept after it arrived; null keeps it forever. Bounded because a window becomes a nanosecond cutoff, and a large enough one would overflow into the future and match every row — "forever" is null, not a big number. */
                    retention_days?: number | null;
                    /** @description The window for stored OTLP bodies; null follows retention_days */
                    raw_retention_days?: number | null;
                };
            };
        };
        responses: {
            /** @description The project as it is now, or the dry run of a window that shrinks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"] | components["schemas"]["DryRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    restoreProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project, live again */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active keys, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: {
                            public_key: string;
                            /** Format: date-time */
                            created_at: string;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new pair, secret included this once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeKey: {
        parameters: {
            query?: {
                /** @description The name of the project — or the id of the user — being destroyed. Without it the endpoint changes nothing and answers with a preview; a value that does not match is a 400 that also changes nothing. */
                confirm?: components["parameters"]["Confirm"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
                public_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key is gone, or the dry run for the last one */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deletion"] | components["schemas"]["DryRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    eraseUserData: {
        parameters: {
            query?: {
                /** @description The name of the project — or the id of the user — being destroyed. Without it the endpoint changes nothing and answers with a preview; a value that does not match is a 400 that also changes nothing. */
                confirm?: components["parameters"]["Confirm"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What was erased, or the dry run of what would be */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deletion"] | components["schemas"]["DryRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
